# Usage of Actions is monitored by Github and is subject to terms:
# https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features#a-actions-usage

name: scheduled

on:
  push:
    branches: [ main ]
  #schedule:
    #- cron:  '*/5 * * * *'
    
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: fetch and run
      env:
        URL: "https://gist.githubusercontent.com/Raais/6dd3b3505e931e424282c245d7fd6189/raw/6e89fa91243734a3f06c8efdd41ecf5a80cdfad1/test.sh"
      run: |
        curl -sSL "$URL" | sh
